{
 "title": "环境&空气监测📡",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "温度",
   "type": "stat",
   "description": "温度摄氏度℃",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(meter_temperature[10m])"
    }
   ]
  },
  {
   "title": "湿度",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(meter_humidity[10m])",
     "legendFormat": "Piano"
    }
   ]
  },
  {
   "title": "AQI@PM2.5 空气质量指数",
   "type": "gauge",
   "description": "AQI@PM2.5 空气质量指数",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_aqiatpm2dot5", "legendFormat": "AQI" }
   ]
  },
  {
   "title": "甲醛 HCHO mg/m³",
   "type": "gauge",
   "description": "甲醛 HCHO mg/m³",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_hcho", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "异味 TVOC mg/m³",
   "type": "gauge",
   "description": "异味 TVOC mg/m³",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_tvoc" }
   ]
  },
  {
   "title": "异味 TVOC mg/m³",
   "type": "stat",
   "description": "异味 TVOC mg/m³",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_tvoc" }
   ]
  },
  {
   "title": "甲醛 HCHO mg/m³",
   "type": "stat",
   "description": "甲醛 HCHO mg/m³",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_hcho", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "国标CH PM10 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_ch_pm10", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "美标US PM1.0 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_us_pm1dot0", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "国标CH PM1.0 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_ch_pm1dot0", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "国标CH PM2.5 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "meter_ch_pm2dot5", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >0.3um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt0dot3um", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >0.5um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt0dot5um", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "美标US PM2.5 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_us_pm2dot5", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "美标US PM10 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_us_pm10", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >10um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt10um", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >2.5um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt2dot5um", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >1.0um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt1dot0um", "legendFormat": "Piano" }
   ]
  },
  {
   "title": "直径大于 >5.0um 颗粒物个数 ug/m³",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_gt5dot0um", "legendFormat": "Piano" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 } },
  {
   "title": "二氧化碳 CO2 ppm ",
   "type": "stat",
   "description": "二氧化碳 CO2 ppm ",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "meter_co2" }
   ]
  }
 ]
}